import { ChatMessage, Room } from "@/app/types/room";

export const mockRooms: Room[] = [
  {
    id: 1,
    title: "Late night thoughts",
    host: "mewmew",
    topic: "Life & feelings",
    listeners: "1.2k",
    color: "#f4b650",
    initials: "M",
    avatar: "#d9795f",
    avatarUrl: "https://i.pravatar.cc/160?img=47",
    location: { name: "Ari", city: "Bangkok", latitude: 13.7804, longitude: 100.5448 },
  },
  {
    id: 2,
    title: "เพลงที่อยากให้เธอฟัง",
    host: "nana.wav",
    topic: "Music lounge",
    listeners: "842",
    color: "#bb88f4",
    initials: "N",
    avatar: "#7653c8",
    avatarUrl: "https://i.pravatar.cc/160?img=32",
    location: { name: "Nimman", city: "Chiang Mai", latitude: 18.7961, longitude: 98.9673 },
  },
  {
    id: 3,
    title: "เริ่มต้นทำธุรกิจยังไงดี",
    host: "goodday",
    topic: "Startup & work",
    listeners: "526",
    color: "#61c7b2",
    initials: "G",
    avatar: "#dc936d",
    avatarUrl: "https://i.pravatar.cc/160?img=12",
    location: { name: "Thonglor", city: "Bangkok", latitude: 13.7307, longitude: 100.5786 },
  },
  {
    id: 4,
    title: "Movie night: Talk to me",
    host: "filmclub",
    topic: "Movies",
    listeners: "304",
    color: "#e977a3",
    initials: "F",
    avatar: "#db6e8a",
    avatarUrl: "https://i.pravatar.cc/160?img=5",
    location: { name: "Old Town", city: "Phuket", latitude: 7.884, longitude: 98.3923 },
  },
];

export const mockMessages: ChatMessage[] = [
  {
    id: "m-1",
    name: "bambam",
    text: "วันนี้เป็นยังไงกันบ้างทุกคน",
    time: "21:42",
    avatar: "#ef8f68",
  },
  {
    id: "m-2",
    name: "junejune",
    text: "เพิ่งเลิกงานเลย ขอเข้ามาฟังด้วยคนนะ",
    time: "21:43",
    avatar: "#6b9ed9",
  },
  {
    id: "m-3",
    name: "pimmy",
    text: "ชอบหัวข้อนี้มาก อยากคุยด้วยจัง",
    time: "21:44",
    avatar: "#b26cc4",
  },
  {
    id: "m-4",
    name: "tonkla",
    text: "กำลังฟังอยู่จากเชียงใหม่ครับ 🌿",
    time: "21:45",
    avatar: "#78b96b",
  },
];
